#####
# This requires a fair bit of memory
# docker-machine create -d virtualbox --virtualbox-memory 4096 default
#####
version: '2'
services:
  domibusa:
    image: mhvdboog/domibus-tomcat
    container_name: domibus_sender
    ports:
      - 3316:3306
      - 8081:8080
      - 9991:9990
    networks:
      - domibus
    environment:
      - ROLE=sender
  domibusb:
    image: mhvdboog/domibus-tomcat
    container_name: domibus_receiver
    ports:
      - 3326:3306
      - 8082:8080
      - 9992:9990
    networks:
      - domibus
    environment:
      - ROLE=receiver
networks:
  domibus:
    driver: bridge
