#####
# This requires a fair bit of memory
# docker-machine create -d virtualbox --virtualbox-memory 4096 default
#####
version: '2'
services:
  domibusa:
    image: mhvdboog/domibus
    container_name: domibusa
    ports:
      - 3316:3306
      - 8081:8080
      - 9991:9990
    networks:
      - domibus
    environment:
      - RECEIVING_MSH_HOST=holodeckb:8082
      - AXIS_PORT=8081
      - ROLE=sender
  domibusb:
    image: mhvdboog/domibus
    container_name: domibusb
    ports:
      - 3326:3306
      - 8082:8080
      - 9992:9990
    networks:
      - domibus
    environment:
      - AXIS_PORT=8082
      - ROLE=receiver
networks:
  domibus:
    driver: bridge
