FROM jboss/wildfly
ADD ./domibus/standalone/deployments/domibus.war /opt/jboss/wildfly/standalone/deployments/
ADD ./domibus/standalone/deployments/domibus-app.war /opt/jboss/wildfly/standalone/deployments/